name: CI

on:
  pull_request: ~
  push:
    branches: [ "master" ]

jobs:
  tests:
    name: "Tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        php-version: ['7.4', '8.0', '8.1', '8.2']
        composer-version: ['v1', 'v2']

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        coverage: none
        tools: composer:${{ matrix.composer-version }}

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ matrix.operating-system }}-php_${{ matrix.php-version }}-composer_${{ matrix.composer-version }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ matrix.operating-system }}-php_${{ matrix.php-version }}-composer_${{ matrix.composer-version }}-composer-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run PHPStan
      run: composer run-script test:phpstan

    - name: Run PHPUnit
      run: composer run-script test:phpunit
